version: "3"

services:
    influxdb:
        container_name: influxdb
        image: influxdb:1.8.5-alpine
        ports:
            - 8088:8088
        privileged: true

    grafana:
        container_name: grafana
        image: grafana/grafana:7.5.5
        volumes:
            - ./grafana/etc:/etc/grafana:ro
            - grafana-log:/var/log/grafana
        links:
            - influxdb:influxdb
        ports:
            - 3000:3000
        depends_on:
            - influxdb
        privileged: true
        
    telegraf:
        container_name: telegraf
        image: telegraf
    
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro       
        ports:
            - 57000:57000
        depends_on:
            - influxdb           
volumes:

  grafana-log:
    external: false
